"""initial

Revision ID: ac1bc1299df6
Revises: 
Create Date: 2024-11-10 19:51:59.480405

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac1bc1299df6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('referral_code',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('Код', sa.String(), nullable=False),
                    sa.Column('Дата создания', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('Дата обновления', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('Дата окончания', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_referral_code_Код'), 'referral_code', ['Код'], unique=True)
    op.create_table('referral',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('Привлекающий пользователь', sa.Integer(),
                              nullable=False),
                    sa.Column('Участник программы', sa.Integer(), nullable=False),
                    sa.Column('Код', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['Код'], ['referral_code.id'], ),
                    sa.ForeignKeyConstraint(['Привлекающий пользователь'],
                                            ['user.id'], ),
                    sa.ForeignKeyConstraint(['Участник программы'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral')
    op.drop_index(op.f('ix_referral_code_Код'), table_name='referral_code')
    op.drop_table('referral_code')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
