"""0002

Revision ID: 82ea953eb22e
Revises: ac1bc1299df6
Create Date: 2024-11-10 21:17:56.614507

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '82ea953eb22e'
down_revision: Union[str, None] = 'ac1bc1299df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'referral_code', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referral_code', type_='unique')
    # ### end Alembic commands ###
